'use client';
import {useCallback,useEffect,useState} from 'react';
import {ArrowRight,ChevronDown,LogOut,Play,UserRound,Video} from 'lucide-react';
import {Lesson,type Props} from './learning';
import {CourseBar} from './course-bar';
import {ActivityStudio} from './activities';
import {LoginDialog,InviteStudents,type AuthStatus} from './student-access';
import {StudentTracker} from './student-tracker';
import {segmentLabel,type SegmentType} from '@/lib/course-flow';
import {formatTime,type Entry,type Lang} from '@/lib/course';
import './interactive.css';
import './atelier.css';
import './editorial.css';
import './reference.css';
import './campus-v2.css';

type VideoItem={id:string;title:string;level:string;lessonNumber:number;lessonTitle:string;duration:number;segmentType:SegmentType;videoUrl:string};
type LearningRecord={lesson_key:string;kind:string;payload:{furthest?:number;position?:number;status?:string};updated_at:string};
const levels=[{id:'기초+초급1',ko:'초급 1',vi:'Sơ cấp 1'},{id:'초급2',ko:'초급 2',vi:'Sơ cấp 2'},{id:'중급1',ko:'중급 1',vi:'Trung cấp 1'},{id:'중급2',ko:'중급 2',vi:'Trung cấp 2'},{id:'TOPIK1',ko:'TOPIK 1',vi:'TOPIK 1'},{id:'TOPIK2 3·4급',ko:'TOPIK 2',vi:'TOPIK 2'}];
function levelGroup(level:string){return level.startsWith('TOPIK2')?'TOPIK2 3·4급':level==='초급회화'?'기초+초급1':level==='중급회화'?'중급1':level;}
function levelName(level:string,lang:Lang){return levels.find(item=>item.id===levelGroup(level))?.[lang]||level;}

export default function Home(){
  const [lang,setLang]=useState<Lang>('vi'),[view,setView]=useState('home'),[auth,setAuth]=useState<AuthStatus|null>(null),[loginOpen,setLoginOpen]=useState(false);
  const [videos,setVideos]=useState<VideoItem[]>([]),[level,setLevel]=useState(levels[0].id),[entries,setEntries]=useState<Entry[]>([]);
  const [learning,setLearning]=useState<LearningRecord[]>([]);
  const [error,setError]=useState(''),[busy,setBusy]=useState(false);
  const [pendingVideo,setPendingVideo]=useState('');
  const t=(ko:string,vi:string)=>lang==='ko'?ko:vi;
  const selectedId=typeof window==='undefined'?'':new URLSearchParams(window.location.search).get('lesson')||'';
  const current=videos.find(item=>item.id===selectedId);
  const teacher=Boolean(auth?.teacher);
  const student=Boolean(auth?.authenticated&&!teacher);
  const visible=videos.filter(item=>levelGroup(item.level)===level);
  const count=(group:string)=>videos.filter(item=>levelGroup(item.level)===group).length;
  const refreshVideos=useCallback(()=>{fetch('/api/course').then(async response=>{if(!response.ok)throw Error();return await response.json() as {videos:VideoItem[]};}).then(data=>setVideos(data.videos)).catch(()=>setError('VIDEO_LIST'));},[]);
  const refreshAuth=useCallback(()=>{fetch('/api/auth').then(async response=>await response.json() as AuthStatus).then(data=>{setAuth(data);if(data.teacher){window.location.hash='teacher';setView('teacher');}}).catch(()=>setAuth({authenticated:false}));},[]);
  const refreshState=useCallback(()=>{if(!selectedId||(!student&&!teacher))return;fetch('/api/state'+window.location.search).then(async response=>{if(!response.ok)throw Error();return await response.json() as {entries:Entry[]};}).then(data=>setEntries(data.entries)).catch(()=>setError('STATE'));},[selectedId,student,teacher]);
  useEffect(()=>{const saved=localStorage.getItem('kross-campus-lang');if(saved==='ko')setLang('ko');const sync=()=>setView(location.hash.slice(1)||'home');sync();window.addEventListener('hashchange',sync);refreshAuth();refreshVideos();return()=>window.removeEventListener('hashchange',sync);},[refreshAuth,refreshVideos]);
  useEffect(()=>{document.documentElement.lang=lang;localStorage.setItem('kross-campus-lang',lang);},[lang]);
  useEffect(()=>{refreshState();},[refreshState]);
  useEffect(()=>{if(!student)return;fetch('/api/my-learning').then(async response=>{if(!response.ok)throw Error();return await response.json() as {records:LearningRecord[]};}).then(data=>setLearning(data.records)).catch(()=>{});},[student]);
  function go(next:string){location.hash=next;setView(next);window.scrollTo(0,0);}
  function openVideo(id:string){if(!student&&!teacher){setPendingVideo(id);setLoginOpen(true);return;}const video=videos.find(item=>item.id===id);if(student&&video&&video.level!==auth?.profile?.course?.level){setError('COURSE_ACCESS');return;}const url=new URL(location.href);url.searchParams.set('lesson',id);url.hash='lesson';location.assign(url.href);}
  async function mutate(body:unknown){setBusy(true);try{const response=await fetch('/api/state'+location.search,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)});const data=await response.json() as {entries?:Entry[];error?:string;correct?:boolean};if(!response.ok)throw Error(data.error||'SAVE_FAILED');if(data.entries)setEntries(data.entries);return data;}finally{setBusy(false);}}
  const props:Props={lang,entries,mutate,busy,go};
  async function logout(){await fetch(teacher?'/api/teacher':'/api/auth',{method:'DELETE'});setAuth({authenticated:false});setEntries([]);const url=new URL(location.href);url.searchParams.delete('lesson');url.hash='home';location.assign(url.href);}
  return <div className="campus-v2">
    <header className="campus-header"><button className="campus-brand" onClick={()=>go('home')} aria-label="KROSS THE MASTER"><b>KROSS</b><small>THE</small><em>Master</em></button><nav aria-label={t('주요 메뉴','Điều hướng chính')}><button className={view==='home'||view==='lesson'?'active':''} onClick={()=>go('home')}>{t('동영상 수업','Bài học video')}</button><button className={view==='words'?'active':''} onClick={()=>go('words')}>{t('단어 / 숙제 제출','Từ vựng / Nộp bài tập')}</button>{student&&<button className={view==='profile'?'active':''} onClick={()=>go('profile')}>{t('나의 학습','Việc học của tôi')}</button>}{teacher&&<button className={view==='teacher'?'active':''} onClick={()=>go('teacher')}>{t('강사 대시보드','Bảng điều khiển giáo viên')}</button>}</nav><div className="campus-header-actions"><button className="language-toggle" onClick={()=>setLang(lang==='ko'?'vi':'ko')}>{lang==='ko'?'KO / VI':'VI / KO'}</button>{auth&&(student||teacher)?<div className="account-actions"><button className="account-button" onClick={()=>go(teacher?'teacher':'profile')}><UserRound size={17}/>{teacher?t('선생님','Giáo viên'):auth.profile?.name||t('내 계정','Tài khoản')}</button><button className="icon-button" onClick={logout} aria-label={t('로그아웃','Đăng xuất')}><LogOut size={17}/></button></div>:<button className="login-button" onClick={()=>setLoginOpen(true)}>{t('로그인','Đăng nhập')}<ArrowRight size={16}/></button>}</div></header>
    {error&&<div className="campus-error" role="alert">{error==='COURSE_ACCESS'?t('배정된 과정의 영상만 볼 수 있습니다.','Bạn chỉ có thể xem video của khóa học được phân.'):error==='VIDEO_LIST'?t('영상 목록을 불러오지 못했습니다.','Không tải được danh sách video.'):t('학습 기록을 불러오지 못했습니다.','Không tải được tiến độ học tập.')} <button onClick={()=>{setError('');refreshVideos();refreshState();}}>{t('닫기','Đóng')}</button></div>}
    {view==='words'?<main className="legacy-word-shell"><iframe title={t('KROSS 단어 연습과 숙제 제출','Luyện từ vựng và nộp bài tập KROSS')} src="/legacy-word/index.html"/></main>:
    view==='teacher'&&teacher?<main className="campus-main teacher-dashboard"><div className="page-heading"><span className="eyebrow">KROSS TEACHING STUDIO</span><h1>{t('강사 대시보드','Bảng điều khiển giáo viên')}</h1><p>{t('영상을 등록하고, 각 영상의 연습과 학생 진도를 관리하세요.','Đăng video, thiết kế bài tập và theo dõi tiến độ từng học viên.')}</p></div><div className="teacher-grid"><section className="teacher-work"><CourseBar lang={lang} teacher initialVideo={current}/>{current&&<ActivityStudio {...props}/>}</section><aside className="teacher-side"><InviteStudents lang={lang}/><StudentTracker lang={lang}/></aside></div></main>:
    view==='profile'&&student?<main className="campus-main"><div className="page-heading"><span className="eyebrow">MY LEARNING</span><h1>{t(auth?.profile?.name||'나',auth?.profile?.name||'Tôi')} · {t('나의 학습','Việc học của tôi')}</h1><p>{t('내 과정의 영상과 학습 기록을 확인하세요.','Xem video và tiến độ học tập của bạn.')}</p></div><div className="profile-overview"><div><small>{t('등록 과정','Khóa học')}</small><strong>{auth?.profile?.course?.title||t('배정된 과정 없음','Chưa có khóa học')}</strong></div><div><small>{t('학습 영상','Video đã học')}</small><strong>{new Set(learning.filter(entry=>entry.kind==='progress').map(entry=>entry.lesson_key)).size}</strong></div><div><small>{t('완료한 연습','Bài tập đã hoàn thành')}</small><strong>{learning.filter(entry=>entry.kind==='activityResponse'&&['correct','completed','approved'].includes(entry.payload.status||'')).length}</strong></div></div><button className="primary" onClick={()=>{setLevel(levelGroup(auth?.profile?.course?.level||levels[0].id));go('home');}}>{t('내 과정 영상 보기','Xem video khóa học')}<ArrowRight size={17}/></button><div className="my-video-progress"><h2>{t('영상별 진도','Tiến độ từng video')}</h2>{videos.filter(item=>item.level===auth?.profile?.course?.level).map(item=>{const record=learning.find(entry=>entry.lesson_key===item.id&&entry.kind==='progress');const seconds=Number(record?.payload.furthest||record?.payload.position||0);return <button key={item.id} onClick={()=>openVideo(item.id)}><span><strong>{item.title}</strong><small>{item.lessonTitle} · {segmentLabel(item.segmentType,lang)}</small></span><span>{Math.min(100,Math.round(seconds/item.duration*100))}%</span></button>})}</div></main>:
    view==='lesson'&&current&&(student||teacher)?<main className="lesson-page"><Lesson key={current.id} {...props}/></main>:
    <main className="campus-main"><div className="library-heading"><div><span className="eyebrow">KROSS THE MASTER · VIDEO CLASS</span><h1>{t('한국어 동영상 수업','Bài học video tiếng Hàn')}</h1><p>{t('과정을 선택하고 영상별 수업을 시작하세요.','Chọn trình độ và bắt đầu học theo từng video.')}</p></div><div className="library-count"><strong>{String(videos.length).padStart(2,'0')}</strong><span>{t('등록된 영상','video bài học')}</span></div></div><div className="level-tabs" role="tablist" aria-label={t('과정 선택','Chọn trình độ')}>{levels.map(item=><button role="tab" aria-selected={level===item.id} className={level===item.id?'selected':''} key={item.id} onClick={()=>setLevel(item.id)}><span>{lang==='ko'?item.ko:item.vi}</span><small>{count(item.id)}</small></button>)}</div><section className="video-library"><div className="library-section-heading"><div><h2>{levelName(level,lang)}</h2><span>{visible.length} {t('개 영상','video')}</span></div><ChevronDown size={18}/></div>{!visible.length?<div className="library-empty"><Video size={34}/><h3>{t('아직 등록된 영상이 없습니다','Chưa có video nào')}</h3><p>{t('강사가 이 과정의 영상을 올리면 여기에 표시됩니다.','Video của khóa học sẽ xuất hiện ở đây khi giáo viên đăng tải.')}</p></div>:<div className="video-grid">{visible.map((item,index)=><button className="video-card" key={item.id} onClick={()=>openVideo(item.id)}><span className="video-visual"><span className="video-number">{String(index+1).padStart(2,'0')}</span><span className="video-play"><Play size={25} fill="currentColor"/></span><span className="video-duration">{formatTime(item.duration)}</span></span><span className="video-card-content"><small>{t(`제${item.lessonNumber}과`,`Bài ${item.lessonNumber}`)} · {segmentLabel(item.segmentType,lang)}</small><strong>{item.title}</strong><span>{item.lessonTitle}</span></span></button>)}</div>}</section></main>}
    <LoginDialog open={loginOpen} onClose={()=>setLoginOpen(false)} lang={lang} onAuthenticated={data=>{setAuth(data);setLoginOpen(false);if(data.teacher)go('teacher');else if(data.authenticated){const target=pendingVideo||selectedId;if(target){const video=videos.find(item=>item.id===target);if(video&&video.level===data.profile?.course?.level){const url=new URL(location.href);url.searchParams.set('lesson',target);url.hash='lesson';location.assign(url.href);}else{setError('COURSE_ACCESS');go('profile');}}else go('profile');}}}/>
  </div>;
}
