'use client';
import {useEffect,useState,type ReactNode} from 'react';
import {ArrowRight,BookOpenCheck,KeyRound,LogIn,ShieldCheck,UserPlus} from 'lucide-react';

type StudentProfile={name:string;email:string;role:string;course:{title:string;level:string}|null};
export type AuthStatus={authenticated:boolean;profile?:StudentProfile|null;teacher?:boolean};

export function LoginDialog({open,onClose,onAuthenticated,lang}:{open:boolean;onClose:()=>void;onAuthenticated:(status:AuthStatus)=>void;lang:string}){
  const [mode,setMode]=useState<'student'|'signup'|'teacher'>('student'),[email,setEmail]=useState(''),[password,setPassword]=useState(''),[name,setName]=useState(''),[code,setCode]=useState(''),[error,setError]=useState(''),[busy,setBusy]=useState(false);
  const t=(ko:string,vi:string)=>lang==='ko'?ko:vi;
  useEffect(()=>{if(!open)return;const escape=(event:KeyboardEvent)=>{if(event.key==='Escape')onClose();};window.addEventListener('keydown',escape);return()=>window.removeEventListener('keydown',escape);},[open,onClose]);
  if(!open)return null;
  async function submit(event:React.FormEvent){event.preventDefault();setBusy(true);setError('');try{
    const response=await fetch(mode==='teacher'?'/api/teacher':'/api/auth',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(mode==='teacher'?{password}:{action:mode==='signup'?'signup':'login',email,password,name,code})});
    const data=await response.json() as AuthStatus&{error?:string};if(!response.ok)throw Error(data.error||'UNAVAILABLE');
    onAuthenticated(mode==='teacher'?{authenticated:false,teacher:true}:data);
  }catch(e){const key=e instanceof Error?e.message:'';setError(key==='LOGIN_FAILED'?t('이메일 또는 비밀번호를 확인하세요.','Kiểm tra email hoặc mật khẩu.'):key==='INVITE_INVALID'?t('초대코드와 이메일을 확인하세요.','Kiểm tra email và mã mời.'):key==='PASSWORD'?t('강사 비밀번호를 확인하세요.','Kiểm tra mật khẩu giáo viên.'):t('로그인할 수 없습니다. 잠시 후 다시 시도하세요.','Không thể đăng nhập. Vui lòng thử lại.'));}finally{setBusy(false);}
  }
  return <div className="login-backdrop" onMouseDown={event=>{if(event.target===event.currentTarget)onClose();}}><section className="login-dialog" role="dialog" aria-modal="true" aria-labelledby="login-title"><div className="login-dialog-head"><span className="eyebrow">KROSS THE MASTER</span><button type="button" onClick={onClose} aria-label={t('닫기','Đóng')}>×</button></div><h2 id="login-title">{mode==='teacher'?t('강사 로그인','Đăng nhập giáo viên'):mode==='signup'?t('초대코드로 가입','Đăng ký bằng mã mời'):t('수업에 로그인','Đăng nhập để học')}</h2><div className="login-tabs"><button type="button" className={mode==='student'?'active':''} onClick={()=>{setMode('student');setError('')}}>{t('학생','Học viên')}</button><button type="button" className={mode==='teacher'?'active':''} onClick={()=>{setMode('teacher');setError('')}}>{t('선생님','Giáo viên')}</button></div><form onSubmit={submit}>{mode==='signup'&&<label>{t('이름','Họ tên')}<input value={name} onChange={event=>setName(event.target.value)} required minLength={2}/></label>}{mode!=='teacher'&&<label>{t('이메일','Email')}<input type="email" value={email} onChange={event=>setEmail(event.target.value)} required autoComplete="email"/></label>}<label>{t('비밀번호','Mật khẩu')}<input type="password" value={password} onChange={event=>setPassword(event.target.value)} required minLength={mode==='teacher'?1:8} autoComplete={mode==='signup'?'new-password':'current-password'}/></label>{mode==='signup'&&<label>{t('초대코드','Mã mời')}<input value={code} onChange={event=>setCode(event.target.value.toUpperCase())} required/></label>}{error&&<p role="alert" className="access-error">{error}</p>}<button className="primary" disabled={busy}>{busy?t('확인 중…','Đang kiểm tra…'):mode==='signup'?t('가입하기','Đăng ký'):t('로그인','Đăng nhập')}</button></form>{mode!=='teacher'&&<button className="signup-switch" onClick={()=>{setMode(mode==='signup'?'student':'signup');setError('')}}>{mode==='signup'?t('이미 계정이 있나요? 로그인','Đã có tài khoản? Đăng nhập'):t('초대코드가 있나요? 가입하기','Có mã mời? Đăng ký')}</button>}</section></div>;
}

export function StudentAccess({lang,children}:{lang:string;children:ReactNode}){
  const [status,setStatus]=useState<AuthStatus|null>(null),[mode,setMode]=useState<'login'|'signup'>('login');
  const [email,setEmail]=useState(''),[password,setPassword]=useState(''),[name,setName]=useState(''),[code,setCode]=useState('');
  const [error,setError]=useState(''),[busy,setBusy]=useState(false),[teacherPassword,setTeacherPassword]=useState('');
  const t=(ko:string,vi:string)=>lang==='ko'?ko:vi;
  useEffect(()=>{fetch('/api/auth').then(async r=>r.json() as Promise<AuthStatus>).then(setStatus).catch(()=>setStatus({authenticated:false}));},[]);
  if(!status)return <main className="access-shell"><div className="access-loading">{t('계정을 확인하고 있어요…','Đang kiểm tra tài khoản…')}</div></main>;
  if(status.authenticated||status.teacher)return <>{children}</>;
  const message=(key:string)=>({INVALID:t('입력 내용을 다시 확인해 주세요. 비밀번호는 8자 이상입니다.','Kiểm tra lại thông tin. Mật khẩu cần ít nhất 8 ký tự.'),INVITE_INVALID:t('이메일과 초대코드가 일치하지 않거나 코드가 만료됐습니다.','Email và mã mời không khớp hoặc mã đã hết hạn.'),EMAIL_EXISTS:t('이미 가입된 이메일입니다. 로그인해 주세요.','Email này đã đăng ký. Hãy đăng nhập.'),LOGIN_FAILED:t('이메일 또는 비밀번호가 맞지 않습니다.','Email hoặc mật khẩu không đúng.'),NOT_CONFIGURED:t('가입 시스템을 준비 중입니다. 잠시 후 다시 시도해 주세요.','Hệ thống đăng ký đang được chuẩn bị. Vui lòng thử lại sau.')}[key]||t('잠시 후 다시 시도해 주세요.','Vui lòng thử lại sau.'));
  return <main className="access-shell">
    <section className="access-brand"><span className="access-wordmark">KROSS <i>THE</i> <em>Master</em></span><div className="access-brand-copy"><span className="eyebrow">LEARN · PRACTICE · SPEAK</span><h1>{t('영상이 멈추면,\n배움이 시작됩니다.','Video dừng lại,\nbài học bắt đầu.')}</h1><p>{t('보고 끝나는 수업이 아니라 직접 말하고, 풀고, 피드백 받는 한국어 수업입니다.','Không chỉ xem bài giảng. Bạn sẽ nói, luyện tập và nhận phản hồi trong từng bài học.')}</p></div><div className="access-points"><span><BookOpenCheck size={19}/>{t('초대받은 수업만 안전하게','Chỉ truy cập lớp được mời')}</span><span><ShieldCheck size={19}/>{t('내 진도와 녹음 자동 저장','Lưu tiến độ và bản ghi âm')}</span></div></section>
    <section className="access-card" aria-labelledby="access-title"><div className="access-tabs" role="tablist"><button className={mode==='login'?'active':''} onClick={()=>{setMode('login');setError('')}}><LogIn size={17}/>{t('로그인','Đăng nhập')}</button><button className={mode==='signup'?'active':''} onClick={()=>{setMode('signup');setError('')}}><UserPlus size={17}/>{t('초대코드로 가입','Đăng ký bằng mã mời')}</button></div>
      <div className="access-heading"><span className="eyebrow">STUDENT ACCESS</span><h2 id="access-title">{mode==='login'?t('다시 만나서 반가워요.','Chào mừng bạn trở lại.'):t('KROSS 수업에 참여하세요.','Tham gia lớp học KROSS.')}</h2><p>{mode==='login'?t('가입한 이메일과 비밀번호를 입력하세요.','Nhập email và mật khẩu đã đăng ký.'):t('학원에서 받은 초대코드는 7일 동안 한 번만 사용할 수 있습니다.','Mã mời từ trung tâm chỉ dùng một lần trong 7 ngày.')}</p></div>
      <form className="access-form" onSubmit={async e=>{e.preventDefault();setBusy(true);setError('');try{const r=await fetch('/api/auth',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({action:mode,email,password,name,code})});const d=await r.json() as AuthStatus&{error?:string};if(!r.ok)throw Error(d.error||'UNAVAILABLE');setStatus(d);}catch(e){setError(message(e instanceof Error?e.message:'UNAVAILABLE'));}finally{setBusy(false);}}}>
        {mode==='signup'&&<label>{t('학생 이름','Tên học viên')}<input value={name} onChange={e=>setName(e.target.value)} autoComplete="name" minLength={2} maxLength={80} placeholder={t('예: Nguyễn Minh Anh','Ví dụ: Nguyễn Minh Anh')} required/></label>}
        <label>{t('이메일','Email')}<input type="email" value={email} onChange={e=>setEmail(e.target.value)} autoComplete="email" placeholder="student@email.com" required/></label><label>{t('비밀번호','Mật khẩu')}<input type="password" value={password} onChange={e=>setPassword(e.target.value)} autoComplete={mode==='login'?'current-password':'new-password'} minLength={8} placeholder={t('8자 이상','Tối thiểu 8 ký tự')} required/></label>
        {mode==='signup'&&<label>{t('초대코드','Mã mời')}<input className="code-input" value={code} onChange={e=>setCode(e.target.value.toUpperCase())} autoCapitalize="characters" maxLength={18} placeholder="A1B2C3D4E5F6G7H8I9" required/></label>}{error&&<p className="access-error" role="alert">{error}</p>}<button className="primary access-submit" disabled={busy}>{busy?t('확인 중…','Đang kiểm tra…'):mode==='login'?t('내 학습 공간 열기','Mở không gian học tập'):t('가입하고 수업 시작하기','Đăng ký và bắt đầu học')}<ArrowRight size={17}/></button>
      </form>
      <details className="teacher-entry"><summary><KeyRound size={15}/>{t('강사 공간으로 들어가기','Vào khu vực giáo viên')}</summary><form onSubmit={async e=>{e.preventDefault();setBusy(true);setError('');try{const r=await fetch('/api/teacher',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({password:teacherPassword})});if(!r.ok)throw Error();location.reload();}catch{setError(t('강사 비밀번호를 확인해 주세요.','Kiểm tra mật khẩu giáo viên.'));setBusy(false);}}}><input aria-label={t('강사 비밀번호','Mật khẩu giáo viên')} type="password" value={teacherPassword} onChange={e=>setTeacherPassword(e.target.value)} placeholder={t('강사 비밀번호','Mật khẩu giáo viên')} required/><button className="secondary" disabled={busy}>{t('강사 공간 열기','Mở khu giáo viên')}</button></form></details>
    </section>
  </main>;
}

export function InviteStudents({lang}:{lang:string}){const [email,setEmail]=useState(''),[level,setLevel]=useState('기초+초급1'),[code,setCode]=useState(''),[error,setError]=useState(''),[busy,setBusy]=useState(false);const t=(ko:string,vi:string)=>lang==='ko'?ko:vi;return <section className="invite-students panel"><span className="eyebrow">CLASS ACCESS</span><h2>{t('학생 초대','Mời học viên')}</h2><p>{t('학생 이메일과 반을 지정해 1회용 가입코드를 만드세요. 코드는 7일 동안 유효합니다.','Chọn email và lớp để tạo mã đăng ký dùng một lần. Mã có hiệu lực trong 7 ngày.')}</p><form onSubmit={async e=>{e.preventDefault();setBusy(true);setError('');setCode('');try{const r=await fetch('/api/enrollment',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({action:'create',email,level})});const d=await r.json() as {code:string};if(!r.ok)throw Error();setCode(d.code);}catch{setError(t('초대코드를 만들지 못했어요.','Không tạo được mã mời.'));}finally{setBusy(false);}}}><label>{t('학생 이메일','Email học viên')}<input type="email" value={email} onChange={e=>setEmail(e.target.value)} required/></label><label>{t('배정 반','Lớp học')}<select value={level} onChange={e=>setLevel(e.target.value)}>{['기초+초급1','초급2','초급회화','중급1','중급2','중급회화','TOPIK1','TOPIK2 3·4급','TOPIK2 5·6급'].map(x=><option key={x}>{x}</option>)}</select></label><button className="primary" disabled={busy}>{busy?t('생성 중…','Đang tạo…'):t('1회용 초대코드 만들기','Tạo mã mời một lần')}</button></form>{code&&<div className="invite-result"><strong>{code}</strong><p>{email} · {level} · {t('7일 유효','Hiệu lực 7 ngày')}</p><button className="secondary" onClick={()=>navigator.clipboard.writeText(code)}>{t('코드 복사','Sao chép mã')}</button></div>}{error&&<p role="alert">{error}</p>}</section>}
