'use client';
import {useEffect,useState,type ReactNode} from 'react';
type Profile={name:string;email:string;level:string};
type Status={teacher:boolean;profile:Profile|null;email:string};
export function StudentAccess({lang,children}:{lang:string;children:ReactNode}){
const [status,setStatus]=useState<Status|null>(null),[error,setError]=useState(''),[busy,setBusy]=useState(false),[code,setCode]=useState(''),[name,setName]=useState(''),[password,setPassword]=useState('');
const t=(ko:string,vi:string)=>lang==='ko'?ko:vi;
function refresh(){fetch('/api/enrollment').then(r=>r.json() as Promise<Status>).then(setStatus).catch(()=>setError(t('연결을 확인해 주세요.','Kiểm tra kết nối.')));}
useEffect(refresh,[]);
if(!status)return <div className="student-access panel">{t('계정을 확인하고 있어요…','Đang kiểm tra tài khoản…')}</div>;
if(status.teacher||status.profile)return <>{children}</>;
return <main className="student-access panel"><span className="eyebrow">KROSS CAMPUS</span><h1>{t('수업 초대 확인','Xác nhận lời mời vào lớp')}</h1><p>{t('KROSS 학생은 학원에서 받은 1회용 초대코드로 반에 등록합니다.','Học viên KROSS dùng mã mời một lần do trung tâm cấp để vào lớp.')}</p>{status.email&&<p className="student-email">{status.email}</p>}
<form onSubmit={async e=>{e.preventDefault();setBusy(true);setError('');try{const r=await fetch('/api/enrollment',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({action:'join',code,name})});const d=await r.json() as {error?:string};if(!r.ok)throw Error(d.error);location.reload();}catch(e){setError(String(e).includes('SIGN_IN_REQUIRED')?t('먼저 ChatGPT로 사이트에 로그인해 주세요.','Hãy đăng nhập vào trang bằng ChatGPT trước.'):t('초대코드와 로그인 이메일을 확인해 주세요.','Kiểm tra mã mời và email đăng nhập.'));setBusy(false);}}}><label>{t('학생 이름','Tên học viên')}<input value={name} onChange={e=>setName(e.target.value)} minLength={2} maxLength={80} required/></label><label>{t('초대코드','Mã mời')}<input value={code} onChange={e=>setCode(e.target.value)} maxLength={18} autoCapitalize="characters" required/></label><button className="primary" disabled={busy}>{t('반에 등록하기','Vào lớp')}</button></form>
<details><summary>{t('강사로 들어가기','Vào khu giáo viên')}</summary><form onSubmit={async e=>{e.preventDefault();setBusy(true);setError('');try{const r=await fetch('/api/teacher',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({password})});if(!r.ok)throw Error();location.reload();}catch{setError(t('강사 비밀번호를 확인해 주세요.','Kiểm tra mật khẩu giáo viên.'));setBusy(false);}}}><label>{t('강사 비밀번호','Mật khẩu giáo viên')}<input type="password" value={password} onChange={e=>setPassword(e.target.value)} required/></label><button className="secondary" disabled={busy}>{t('강사 공간 열기','Mở khu giáo viên')}</button></form></details>{error&&<p role="alert">{error}</p>}</main>;
}
export function InviteStudents({lang}:{lang:string}){const [email,setEmail]=useState(''),[level,setLevel]=useState('기초+초급1'),[code,setCode]=useState(''),[error,setError]=useState(''),[busy,setBusy]=useState(false);const t=(ko:string,vi:string)=>lang==='ko'?ko:vi;return <section className="invite-students panel"><span className="eyebrow">CLASS ACCESS</span><h2>{t('학생 초대','Mời học viên')}</h2><p>{t('학생의 ChatGPT 로그인 이메일로 사이트 방문을 허용한 뒤 초대코드를 전달하세요. 코드는 7일 동안 한 번만 사용할 수 있습니다.','Cho phép email ChatGPT của học viên truy cập trang, sau đó gửi mã mời. Mã dùng một lần trong 7 ngày.')}</p><form onSubmit={async e=>{e.preventDefault();setBusy(true);setError('');setCode('');try{const r=await fetch('/api/enrollment',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({action:'create',email,level})});const d=await r.json() as {code:string};if(!r.ok)throw Error();setCode(d.code);}catch{setError(t('초대코드를 만들지 못했어요.','Không tạo được mã mời.'));}finally{setBusy(false);}}}><label>{t('학생 로그인 이메일','Email đăng nhập của học viên')}<input type="email" value={email} onChange={e=>setEmail(e.target.value)} required/></label><label>{t('배정 반','Lớp học')}<select value={level} onChange={e=>setLevel(e.target.value)}>{['기초+초급1','초급2','초급회화','중급1','중급2','중급회화','TOPIK1','TOPIK2 3·4급','TOPIK2 5·6급'].map(x=><option key={x}>{x}</option>)}</select></label><button className="primary" disabled={busy}>{t('1회용 초대코드 만들기','Tạo mã mời một lần')}</button></form>{code&&<div className="invite-result"><strong>{code}</strong><p>{email} · {level} · {t('7일 유효','Hiệu lực 7 ngày')}</p><button className="secondary" onClick={()=>navigator.clipboard.writeText(code)}>{t('코드 복사','Sao chép mã')}</button></div>}{error&&<p role="alert">{error}</p>}</section>}
