'use client';
import {useEffect,useState,type ReactNode} from 'react';
import {LockKeyhole} from 'lucide-react';
export function TeacherGate({children,lang}:{children:ReactNode;lang:string}){const [state,setState]=useState('loading'),[password,setPassword]=useState(''),[error,setError]=useState(''),[busy,setBusy]=useState(false);const t=(ko:string,vi:string)=>lang==='ko'?ko:vi;
useEffect(()=>{let alive=true;fetch('/api/teacher').then(async r=>await r.json() as {authenticated?:boolean}).then(d=>{if(alive)setState(d.authenticated?'open':'locked');}).catch(()=>{if(alive){setState('locked');setError(t('연결을 확인해 주세요.','Kiểm tra kết nối.'));}});const lock=()=>setState('locked');window.addEventListener('kross-teacher-locked',lock);return()=>{alive=false;window.removeEventListener('kross-teacher-locked',lock);};},[]);
if(state==='loading')return <p role="status">{t('접근 권한 확인 중…','Đang kiểm tra quyền truy cập…')}</p>;
if(state==='open')return <><div className="teacher-session"><span><LockKeyhole size={15}/>{t('강사 공간 · 8시간 후 자동 잠금','Khu giáo viên · tự khóa sau 8 giờ')}</span><button className="secondary" disabled={busy} onClick={async()=>{setBusy(true);try{const r=await fetch('/api/teacher',{method:'DELETE'});if(!r.ok)throw Error();setState('locked');}catch{setError(t('잠금에 실패했어요. 다시 시도하세요.','Không thể khóa. Hãy thử lại.'));}finally{setBusy(false);}}}>{t('잠그고 나가기','Khóa khu giáo viên')}</button></div>{error&&<p role="alert">{error}</p>}{children}</>;
return <form className="teacher-login panel" onSubmit={async e=>{e.preventDefault();setBusy(true);setError('');try{const r=await fetch('/api/teacher',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({password})});if(r.ok){setPassword('');setState('open');}else setError(r.status===429?t('시도가 많습니다. 15분 후 다시 시도하세요.','Quá nhiều lần thử. Vui lòng thử lại sau 15 phút.'):t('비밀번호를 확인해 주세요.','Vui lòng kiểm tra mật khẩu.'));}catch{setError(t('연결을 확인해 주세요.','Kiểm tra kết nối.'));}finally{setBusy(false);}}}><LockKeyhole size={30}/><span className="eyebrow">KROSS TEACHING STUDIO</span><h1>{t('강사 전용 공간','Khu vực giáo viên')}</h1><p>{t('강사 비밀번호를 입력해 주세요.','Nhập mật khẩu giáo viên để tiếp tục.')}</p><label htmlFor="teacher-password">{t('비밀번호','Mật khẩu')}</label><input id="teacher-password" type="password" value={password} onChange={e=>setPassword(e.target.value)} autoComplete="current-password" maxLength={128} required/>{error&&<p role="alert">{error}</p>}<button className="primary" disabled={busy}>{busy?t('확인 중…','Đang kiểm tra…'):t('강사 공간 들어가기','Vào khu giáo viên')}</button></form>;
}
