import { database } from '@/db';
const namespace='__teacher_auth__';
export const cookieName='kross_teacher';
export async function digest(value:string){return Array.from(new Uint8Array(await crypto.subtle.digest('SHA-256',new TextEncoder().encode(value)))).map(x=>x.toString(16).padStart(2,'0')).join('');}
export function cookie(req:Request){return req.headers.get('cookie')?.split(';').map(x=>x.trim()).find(x=>x.startsWith(cookieName+'='))?.slice(cookieName.length+1)||'';}
export async function isTeacher(req:Request){const token=cookie(req);if(!/^[a-f0-9]{64}$/.test(token))return false;const row=await database().prepare('SELECT payload FROM records WHERE session=? AND id=?').bind(namespace,await digest(token)).first<{payload:string}>();return !!row && JSON.parse(row.payload).expires>Date.now();}
export async function putAuth(id:string,payload:unknown){await database().prepare('INSERT INTO records(session,id,kind,payload,updated_at) VALUES (?,?,?,?,?) ON CONFLICT(session,id) DO UPDATE SET payload=excluded.payload,updated_at=excluded.updated_at').bind(namespace,id,'auth',JSON.stringify(payload),new Date().toISOString()).run();}
export async function verifyPassword(password:string){const key=await crypto.subtle.importKey('raw',new TextEncoder().encode(password),'PBKDF2',false,['deriveBits']);const bits=await crypto.subtle.deriveBits({name:'PBKDF2',salt:new TextEncoder().encode('86e5c1f8375004b35f6975fe0354df09'),iterations:100000,hash:'SHA-256'},key,256);const expected='8c2d6d13cc0eeae6df2ea116500bbd12deb3fab702fbd4e5e1af8969ebfcf359';const actual=Array.from(new Uint8Array(bits)).map(x=>x.toString(16).padStart(2,'0')).join('');let difference=0;for(let i=0;i<expected.length;i++)difference|=expected.charCodeAt(i)^actual.charCodeAt(i);return difference===0;}
export async function loginAllowed(req:Request){const id='rate:'+await digest(req.headers.get('cf-connecting-ip')||req.headers.get('oai-authenticated-user-id')||'local');const bucket=Math.floor(Date.now()/900000);const key=id+':'+bucket;await database().prepare("INSERT INTO records(session,id,kind,payload,updated_at) VALUES (?,?,'rate','1',?) ON CONFLICT(session,id) DO UPDATE SET payload=CAST(CAST(payload AS INTEGER)+1 AS TEXT)").bind(namespace,key,new Date().toISOString()).run();const r=await database().prepare('SELECT payload FROM records WHERE session=? AND id=?').bind(namespace,key).first<{payload:string}>();return Number(r?.payload)<=10;}
